### ISSUE TITLE
DEBIAN_FRONTEND noninteractive definirlo una unica vez

### ISSUE THREAD

**Issue by keopx** [juanjol/docker-drupal-nginx#1]
@juanjol https://github.com/juanjol/docker-drupal-nginx/blob/master/Dockerfile#L19 no es necesario ponerlo siempre.

Con definirlo al principio es suficiente:

```
# Set frontend. We'll clean this later on!
ENV DEBIAN_FRONTEND noninteractive
```

**Comment by juanjol** [comment]
Si definimos esa variable de forma general, apt queda inservible dentro del contenedor, por lo que podría dificultar algunos trabajos en un entorno ya montado, así que se queda como está.
